# Generated by Django 3.1.8 on 2021-05-15 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210514_1600'),
    ]

    