# Generated by Django 3.1.8 on 2021-05-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210524_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='bvn',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('cit', models.CharField(max_length=22)),
                ('cat1', models.CharField(max_length=22)),
                ('cat2', models.CharField(max_length=22)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
