# Generated by Django 3.1.8 on 2021-05-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_bvn'),
    ]

    operations = [
        migrations.AddField(
            model_name='bvn',
            name='cat3',
            field=models.CharField(default='', editable=False, max_length=22),
        ),
    ]
