# Generated by Django 3.1.8 on 2021-05-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_bvn_cat3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bvn',
            name='cat3',
            field=models.CharField(default='', max_length=22),
        ),
    ]
