# Generated by Django 3.1.8 on 2021-05-26 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_bvn_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bvn',
            name='entry',
        ),
        migrations.AddField(
            model_name='bvn',
            name='entry1',
            field=models.CharField(default='', max_length=22),
        ),
        migrations.AddField(
            model_name='bvn',
            name='entry2',
            field=models.CharField(default='', max_length=22),
        ),
    ]
