# Generated by Django 3.1.8 on 2021-05-26 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210525_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bvn',
            name='cit',
        ),
    ]
