# Generated by Django 3.1.8 on 2021-05-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_bvn_cit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bvn',
            name='area',
            field=models.CharField(max_length=120),
        ),
    ]
