# Generated by Django 3.1.8 on 2021-05-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210525_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='bvn',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='bvn',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
