# Generated by Django 3.1.8 on 2021-05-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20210525_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bvn',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
    ]
