# Generated by Django 3.1.8 on 2021-05-26 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20210525_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bvn',
            name='ph',
        ),
    ]
