# Generated by Django 3.1.8 on 2021-05-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20210525_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bvn',
            name='phone',
            field=models.CharField(default='', max_length=120),
        ),
    ]
