# Generated by Django 3.1.8 on 2021-05-26 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20210525_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bvn',
            name='email',
        ),
        migrations.RemoveField(
            model_name='bvn',
            name='phone',
        ),
    ]
