# Generated by Django 3.1.8 on 2021-05-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20210525_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='bvn',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='bvn',
            name='phone',
            field=models.CharField(default='', max_length=120),
        ),
    ]
