# Generated by Django 3.1.8 on 2021-05-26 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20210525_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bvn',
            old_name='phone',
            new_name='ph',
        ),
    ]
