# Generated by Django 3.1.8 on 2021-05-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20210525_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bvn',
            name='email',
        ),
        migrations.RemoveField(
            model_name='bvn',
            name='ph',
        ),
        migrations.AddField(
            model_name='bvn',
            name='oiw',
            field=models.CharField(default='', max_length=22),
        ),
    ]
