# Generated by Django 3.1.8 on 2021-05-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='hotel',
        ),
        migrations.AddField(
            model_name='room',
            name='beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(choices=[('YAY', 'AC'), ('NAC', 'NON-AC'), ('DEL', 'DELUX')], max_length=3),
        ),
    ]
