# Generated by Django 3.1.8 on 2021-05-28 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20210527_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('DEL', 'DELUX'), ('YAY', 'AC'), ('NAC', 'NON-AC')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
