# Generated by Django 3.1.8 on 2021-06-02 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0037_auto_20210527_2144'),
    ]

    operations = [
    
        migrations.RemoveField(
            model_name='booking',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='restaura',
            name='types',
        ),
        migrations.AddField(
            model_name='baroda',
            name='cat4',
            field=models.CharField(default='', max_length=22),
        ),
        migrations.AddField(
            model_name='baroda',
            name='cat5',
            field=models.CharField(default='', max_length=22),
        ),
        migrations.AddField(
            model_name='booking',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bvn',
            name='cat4',
            field=models.CharField(default='', max_length=22),
        ),
        migrations.AddField(
            model_name='bvn',
            name='cat5',
            field=models.CharField(default='', max_length=22),
        ),
        migrations.AddField(
            model_name='restaura',
            name='url',
            field=models.CharField(default='', max_length=22),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bvn',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='restaura',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.bvn'),
        ),
        migrations.AlterField(
            model_name='restaura',
            name='phone1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='category',
            field=models.CharField(choices=[('DELUX', 'DELUX'), ('AC', 'AC'), ('NON-AC', 'NON-AC')], default='AC', max_length=10),
        ),
    ]
