# Generated by Django 3.1.8 on 2021-06-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_auto_20210602_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='hotel',
        ),
        migrations.AlterField(
            model_name='rooms',
            name='category',
            field=models.CharField(choices=[('AC', 'AC'), ('DELUX', 'DELUX'), ('NON-AC', 'NON-AC')], default='AC', max_length=10),
        ),
    ]
