# Generated by Django 3.1.8 on 2021-06-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_auto_20210606_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='category',
            field=models.CharField(choices=[('AC', 'AC'), ('DELUX', 'DELUX'), ('NON-AC', 'NON-AC')], default='AC', max_length=10),
        ),
    ]
