# Generated by Django 3.1.8 on 2021-06-08 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_auto_20210606_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='home.bvn'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='category',
            field=models.CharField(choices=[('NON-AC', 'NON-AC'), ('DELUX', 'DELUX'), ('AC', 'AC')], default='AC', max_length=10),
        ),
    ]
