# Generated by Django 3.1.8 on 2021-06-08 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_auto_20210607_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.bvn'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='category',
            field=models.CharField(choices=[('NON-AC', 'NON-AC'), ('AC', 'AC'), ('DELUX', 'DELUX')], default='AC', max_length=10),
        ),
    ]
