# Generated by Django 3.1.8 on 2021-06-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_auto_20210607_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='category',
            field=models.CharField(choices=[('AC', 'AC'), ('NON-AC', 'NON-AC'), ('DELUX', 'DELUX')], default='AC', max_length=10),
        ),
    ]
