# Generated by Django 3.1.8 on 2021-06-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_auto_20210607_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='capacity',
        ),
        migrations.AddField(
            model_name='rooms',
            name='image',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rooms',
            name='category',
            field=models.CharField(choices=[('DELUX', 'DELUX'), ('NON-AC', 'NON-AC'), ('AC', 'AC')], default='AC', max_length=10),
        ),
    ]
