# Generated by Django 3.1.8 on 2021-06-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_auto_20210607_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='category',
            field=models.CharField(choices=[('NON-AC', 'NON-AC'), ('AC', 'AC'), ('DELUX', 'DELUX')], default='AC', max_length=10),
        ),
    ]
