# Generated by Django 3.1.8 on 2021-06-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_auto_20210614_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='category',
            field=models.CharField(choices=[('AC', 'AC'), ('NON-AC', 'NON-AC'), ('DELUX', 'DELUX')], default='AC', max_length=10),
        ),
    ]
